version: '3'

services:
  hnode:
    container_name: hnode
    image: "hnode:${TAG:-latest}"
    network_mode: host
    build:
      context: "."
      dockerfile: Dockerfile
    mem_limit: 2GB
    tty: true
    environment:
      PRIVATE_KEY: ${ETH_PRIVATE_KEY}
      MINING_INTERVAL: ${MINING_INTERVAL:-1000}
